### ISSUE TITLE
有关MCMC_dina模型的问题

### ISSUE THREAD

**Issue by zelo2** [inuyasha2012/pypsy#6]
老师您好，最近在使用您的pypsy包做实验，目前有两个问题想请教一下：
1、请问老师是如何实现程序占用cpu多核？我自己写认知诊断模型时只能占用CPU的单核导致速度太慢。
2、我在测试MCMC方法的DINA模型时会出现当数据规模增长到一定程度，执行时间从几十秒骤增到几千秒的问题，这是因为内存不够导致的嘛（因为我发现在内存的占用会随着训练数据集规模的增大而增大）？

**Comment by inuyasha2012** [comment]
我没有用多核啊，MCMC尤其是随机游走本事就很慢，我的微信号407162，有空微信上沟通
